---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-vk-io--owner-v1-application
  failurePolicy: Fail
  name: mapplication.kb.io
  rules:
  - apiGroups:
    - apps.vk.io--owner
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-canary-vk-io--owner-v2-application
  failurePolicy: Fail
  name: mapplication.kb.io
  rules:
  - apiGroups:
    - apps-canary.vk.io--owner
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-vk-io--owner-v1-application
  failurePolicy: Fail
  name: vapplication.kb.io
  rules:
  - apiGroups:
    - apps.vk.io--owner
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-canary-vk-io--owner-v2-application
  failurePolicy: Fail
  name: vapplication.kb.io
  rules:
  - apiGroups:
    - apps-canary.vk.io--owner
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
